#!/usr/bin/env python3
"""
extract-legal-sources.py

Walks HvA_full_dmn_export.dmn's <dmn:authorityRequirement> -> <dmn:knowledgeSource>
links, resolves each into HvA_annotaties.xml's <concept> (CPT) / <textannotation>
(APT) registries, and produces a decision-by-decision map of the legal sources
each decision actually declares: the named source document (+ BWB number where
one exists), the JuriConnect (JCI) article citation where present, and the
grounding quote(s) pulled from the annotation export.

This is a read-only extraction over the *original*, unpatched exports — it does
not touch the DMN content itself and has no bearing on the FEEL-evaluation fix
in HvA_full_dmn_export-patched.dmn. See legal-sources-hva.md (generated by this
script) for the results and how to read them.

Usage:
    python extract-legal-sources.py
    python extract-legal-sources.py --dmn ../HvA_full_dmn_export.dmn \
        --annotations ../HvA_annotaties.xml \
        --json legal-sources-hva.json --markdown legal-sources-hva.md

Requires: lxml (HvA_annotaties.xml is not well-formed XML — a handful of
attribute values contain unescaped nested quotes — so this uses lxml's
recovering parser rather than the stdlib xml.etree, which refuses the file
outright).
"""
import argparse
import json
import re
import sys
from collections import OrderedDict
from pathlib import Path

from lxml import etree

DMN_NS = {"dmn": "https://www.omg.org/spec/DMN/20191111/MODEL/"}
UUID_RE = re.compile(r"[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}")


def load_dmn(path):
    tree = etree.parse(str(path))
    root = tree.getroot()

    knowledge_sources = OrderedDict()
    for ks in root.iter("{%s}knowledgeSource" % DMN_NS["dmn"]):
        ks_id = ks.get("id")
        desc_el = ks.find("dmn:description", DMN_NS)
        type_el = ks.find("dmn:type", DMN_NS)
        desc = (desc_el.text or "").strip() if desc_el is not None else ""
        typ = (type_el.text or "").strip() if type_el is not None else ""
        m = UUID_RE.search(desc)
        knowledge_sources[ks_id] = {
            "id": ks_id,
            "name": ks.get("name"),
            "description": desc,
            "type": typ,
            "ref_id": m.group(0) if m else None,
        }

    decisions = []
    for d in root.findall("dmn:decision", DMN_NS):
        d_id = d.get("id")
        d_name = d.get("name")
        auth_ids = []
        for ar in d.findall("dmn:authorityRequirement", DMN_NS):
            ra = ar.find("dmn:requiredAuthority", DMN_NS)
            if ra is not None:
                href = (ra.get("href") or "").lstrip("#")
                if href:
                    auth_ids.append(href)
        decisions.append({"id": d_id, "name": d_name, "knowledge_source_ids": auth_ids})

    return decisions, knowledge_sources


def _text(el, attr):
    v = el.get(attr)
    return v.strip() if v else None


def load_annotations(path):
    parser = etree.XMLParser(recover=True)
    tree = etree.parse(str(path), parser)
    root = tree.getroot()

    documents = {}
    for doc in root.iter("document"):
        doc_id = _text(doc, "id")
        if not doc_id:
            continue
        documents[doc_id] = {
            "id": doc_id,
            "name": _text(doc, "name"),
            "type": _text(doc, "type"),
            "url": _text(doc, "url"),
            "version": _text(doc, "version"),
            "bwb": _bwb_from_name(_text(doc, "name")),
        }

    concepts = {}
    for c in root.iter("concept"):
        c_id = _text(c, "id")
        if not c_id:
            continue
        concepts[c_id] = {"id": c_id, "name": _text(c, "name"), "type": _text(c, "type")}

    textannotations = {}
    concept_to_annotations = {}
    for ta in root.iter("textannotation"):
        ta_id = _text(ta, "id")
        if not ta_id:
            continue
        text_el = ta.find("text")
        quote = (text_el.text or "").strip() if text_el is not None and text_el.text else ""
        quote = re.sub(r"\s+", " ", quote)
        props = {}
        for prop in ta.iter("property"):
            pname = _text(prop, "name")
            pval = _text(prop, "value")
            if pname:
                props[pname] = pval
        entry = {
            "id": ta_id,
            "name": _text(ta, "name"),
            "type": _text(ta, "type"),
            "document_id": _text(ta, "document"),
            "concept_id": _text(ta, "concept"),
            "juriconnect": _text(ta, "juriconnect"),
            "quote": quote,
            "properties": props,
        }
        textannotations[ta_id] = entry
        if entry["concept_id"]:
            concept_to_annotations.setdefault(entry["concept_id"], []).append(ta_id)

    return documents, concepts, textannotations, concept_to_annotations


def _bwb_from_name(name):
    if not name:
        return None
    m = re.match(r"^(BWBR\d+)$", name.strip())
    return m.group(1) if m else None


def resolve_knowledge_source(ks, documents, concepts, textannotations, concept_to_annotations):
    """Return a dict describing what the knowledge source actually resolves to."""
    result = {
        "knowledge_source_name": ks["name"],
        "knowledge_source_type": ks["type"],
        "ref_id": ks["ref_id"],
        "resolved": False,
        "documents": [],
        "jci_citations": [],
        "quotes": [],
    }
    if ks["ref_id"] is None:
        return result

    if ks["type"] == "APT":
        ta = textannotations.get(ks["ref_id"])
        if ta is None:
            return result
        result["resolved"] = True
        _absorb_annotation(result, ta, documents)

    elif ks["type"] == "CPT":
        concept = concepts.get(ks["ref_id"])
        if concept is None:
            return result
        result["resolved"] = True
        result["concept_name"] = concept["name"]
        result["concept_type"] = concept["type"]
        for ta_id in concept_to_annotations.get(ks["ref_id"], []):
            ta = textannotations.get(ta_id)
            if ta:
                _absorb_annotation(result, ta, documents)

    return result


def _absorb_annotation(result, ta, documents):
    if ta["document_id"] and ta["document_id"] in documents:
        doc = documents[ta["document_id"]]
        if doc not in result["documents"]:
            result["documents"].append(doc)
    if ta["juriconnect"] and ta["juriconnect"] not in result["jci_citations"]:
        result["jci_citations"].append(ta["juriconnect"])
    if ta["quote"] and ta["quote"] not in result["quotes"]:
        result["quotes"].append(ta["quote"])


def build_mapping(dmn_path, annotations_path):
    decisions, knowledge_sources = load_dmn(dmn_path)
    documents, concepts, textannotations, concept_to_annotations = load_annotations(annotations_path)

    mapping = []
    for d in decisions:
        legal_basis = []
        for ks_id in d["knowledge_source_ids"]:
            ks = knowledge_sources.get(ks_id)
            if ks is None:
                legal_basis.append({"knowledge_source_name": None, "resolved": False, "error": f"unknown knowledgeSource id {ks_id}"})
                continue
            legal_basis.append(resolve_knowledge_source(ks, documents, concepts, textannotations, concept_to_annotations))
        mapping.append({"decision_id": d["id"], "decision_name": d["name"], "legal_basis": legal_basis})

    stats = {
        "total_decisions": len(decisions),
        "decisions_with_authority": sum(1 for d in decisions if d["knowledge_source_ids"]),
        "total_knowledge_sources": len(knowledge_sources),
        "knowledge_sources_by_type": {
            "CPT": sum(1 for ks in knowledge_sources.values() if ks["type"] == "CPT"),
            "APT": sum(1 for ks in knowledge_sources.values() if ks["type"] == "APT"),
        },
        "total_documents": len(documents),
        "total_concepts": len(concepts),
        "total_textannotations": len(textannotations),
        "total_distinct_jci_citations": len({ta["juriconnect"] for ta in textannotations.values() if ta["juriconnect"]}),
        "total_textannotations_with_jci": sum(1 for ta in textannotations.values() if ta["juriconnect"]),
    }

    # resolution counts
    resolved = 0
    unresolved = []
    for d in mapping:
        for lb in d["legal_basis"]:
            if lb.get("resolved"):
                resolved += 1
            else:
                unresolved.append((d["decision_name"], lb.get("knowledge_source_name")))
    stats["knowledge_sources_resolved"] = resolved
    stats["knowledge_sources_unresolved"] = len(unresolved)

    return mapping, stats, documents, unresolved


def render_markdown(mapping, stats, documents, unresolved):
    lines = []
    lines.append("# Applicable legal sources — `HvA_full_dmn_export.dmn`")
    lines.append("")
    lines.append(
        "Generated by [`extract-legal-sources.py`](extract-legal-sources.py) from the "
        "**original** `HvA_full_dmn_export.dmn` and `HvA_annotaties.xml` — read-only, "
        "regenerate any time either file is re-exported:"
    )
    lines.append("")
    lines.append("```bash")
    lines.append("cd examples/organizations/amsterdam/testCases")
    lines.append("python extract-legal-sources.py")
    lines.append("```")
    lines.append("")
    lines.append(
        "Walks every decision's `<dmn:authorityRequirement>` → `<dmn:knowledgeSource>` "
        "link, resolves the CPT (concept) or APT (text annotation) id it points at against "
        "`HvA_annotaties.xml`'s own registries, and reports the named source document "
        "(with its BWB number where the document *is* a national law), the JuriConnect "
        "(JCI) article-level citation where the underlying annotation carries one, and the "
        "grounding quote itself. Also emits [`legal-sources-hva.json`](legal-sources-hva.json) "
        "with the full, unabridged data (untrimmed quotes, every matched document/citation) "
        "for anything that wants to consume this programmatically."
    )
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append("| Metric | Count |")
    lines.append("| --- | --- |")
    lines.append(f"| Decisions in the DRD | {stats['total_decisions']} |")
    lines.append(f"| Decisions with ≥ 1 `authorityRequirement` | {stats['decisions_with_authority']} |")
    lines.append(f"| Distinct `knowledgeSource` links | {stats['total_knowledge_sources']} (CPT {stats['knowledge_sources_by_type']['CPT']} / APT {stats['knowledge_sources_by_type']['APT']}) |")
    lines.append(f"| `knowledgeSource` links resolved into the annotation export | {stats['knowledge_sources_resolved']} / {stats['knowledge_sources_resolved'] + stats['knowledge_sources_unresolved']} |")
    lines.append(f"| Named source documents in the registry | {stats['total_documents']} |")
    lines.append(f"| Concepts (CPT) in the registry | {stats['total_concepts']} |")
    lines.append(f"| Text annotations (APT / quotes) in the registry | {stats['total_textannotations']} |")
    lines.append(f"| Text annotations carrying a JuriConnect citation | {stats['total_textannotations_with_jci']} |")
    lines.append(f"| Distinct JuriConnect (JCI) article citations among them | {stats['total_distinct_jci_citations']} |")
    lines.append("")

    if unresolved:
        lines.append("**Unresolved links** (knowledgeSource id doesn't match anything in the annotation export):")
        lines.append("")
        for dname, ksname in unresolved:
            lines.append(f"- `{dname}` → `{ksname}`")
        lines.append("")

    lines.append("## Known data-quality caveats")
    lines.append("")
    lines.append(
        "- **`HvA_annotaties.xml` is not well-formed XML** — a handful of `<property>` "
        "attribute values contain unescaped nested double quotes. Parsed with lxml's "
        "recovering parser, which drops only the malformed fragment, not the surrounding "
        "document; one `<textannotation>` out of the file's 359 was lost this way (358 "
        "recovered here). Not something this script can fix — it's a defect in the "
        "source export, independent of the FEEL-evaluation fix in "
        "`HvA_full_dmn_export-patched.dmn`."
    )
    lines.append(
        "- **2 documents' `name` is just their raw BWB number** (`BWBR0005416`, "
        "`BWBR0035362`) with no human-readable title filled in on the source side — "
        "shown as-is above."
    )
    if unresolved:
        n_dangling = len({ksname for _, ksname in unresolved})
        lines.append(
            f"- **{len(unresolved)} `authorityRequirement` link(s)** (across "
            f"{len({dname for dname, _ in unresolved})} decision(s), {n_dangling} distinct "
            "dangling `knowledgeSource`) point at a CPT/APT id that isn't in the annotation "
            "export at all — see \"Unresolved links\" above."
        )
    lines.append(
        f"- Only **{stats['total_textannotations_with_jci']} of {stats['total_textannotations']}** "
        "text annotations carry an article-level JuriConnect citation at all (~"
        f"{round(100 * stats['total_textannotations_with_jci'] / stats['total_textannotations'])}%), "
        f"and those {stats['total_textannotations_with_jci']} share only "
        f"**{stats['total_distinct_jci_citations']} distinct citation values** between them (the "
        "same article commonly grounds several separately-quoted concepts). The rest ground to "
        "a named document and a quote, but not a specific article — that's a real gap in what "
        "iKnow's export captured, not something this script can infer."
    )
    lines.append("")

    lines.append("## Named source documents")
    lines.append("")
    lines.append("Every document in `HvA_annotaties.xml`'s `<documents>` registry, whether or not a decision currently cites it:")
    lines.append("")
    lines.append("| Document | Type | BWB |")
    lines.append("| --- | --- | --- |")
    for doc in sorted(documents.values(), key=lambda d: (d["name"] or "")):
        bwb = f"`{doc['bwb']}`" if doc["bwb"] else "—"
        lines.append(f"| {doc['name']} | {doc['type'] or '—'} | {bwb} |")
    lines.append("")
    lines.append("---")
    lines.append("")

    lines.append("## Per-decision legal basis")
    lines.append("")
    for d in mapping:
        lines.append(f"### {d['decision_name']}")
        lines.append("")
        lines.append(f"`{d['decision_id']}`")
        lines.append("")
        if not d["legal_basis"]:
            lines.append("_No `authorityRequirement` declared on this decision._")
            lines.append("")
            continue
        for lb in d["legal_basis"]:
            ks_name = lb.get("knowledge_source_name") or "(unnamed)"
            if not lb.get("resolved"):
                lines.append(f"- **{ks_name}** — unresolved (id `{lb.get('ref_id')}` not found in the annotation export)")
                continue
            ks_type = lb.get("knowledge_source_type")
            header = f"- **{ks_name}** ({ks_type})"
            if lb.get("concept_name"):
                header += f" — concept: _{lb['concept_name']}_"
            lines.append(header)
            if lb["documents"]:
                for doc in lb["documents"]:
                    bwb = f", BWB `{doc['bwb']}`" if doc["bwb"] else ""
                    lines.append(f"  - Document: {doc['name']} ({doc['type'] or 'unknown type'}{bwb})")
            else:
                lines.append("  - Document: (none referenced by the matched annotation)")
            if lb["jci_citations"]:
                for jci in lb["jci_citations"]:
                    lines.append(f"  - JCI citation: `{jci}`")
            else:
                lines.append("  - JCI citation: none (quote/document only, no article-level citation)")
            if lb["quotes"]:
                shown = lb["quotes"][:2]
                for q in shown:
                    excerpt = q if len(q) <= 220 else q[:220] + "…"
                    lines.append(f"  - Quote: “{excerpt}”")
                extra = len(lb["quotes"]) - len(shown)
                if extra > 0:
                    lines.append(f"  - (+{extra} more quote(s) grounding this concept — see the JSON file)")
        lines.append("")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    here = Path(__file__).parent
    ap.add_argument("--dmn", default=str(here / ".." / "HvA_full_dmn_export.dmn"))
    ap.add_argument("--annotations", default=str(here / ".." / "HvA_annotaties.xml"))
    ap.add_argument("--json", default=str(here / "legal-sources-hva.json"))
    ap.add_argument("--markdown", default=str(here / "legal-sources-hva.md"))
    args = ap.parse_args()

    mapping, stats, documents, unresolved = build_mapping(args.dmn, args.annotations)

    with open(args.json, "w", encoding="utf-8") as f:
        json.dump({"stats": stats, "decisions": mapping}, f, ensure_ascii=False, indent=2)

    md = render_markdown(mapping, stats, documents, unresolved)
    with open(args.markdown, "w", encoding="utf-8") as f:
        f.write(md)

    print(f"Decisions: {stats['total_decisions']} ({stats['decisions_with_authority']} with authorityRequirement)")
    print(f"knowledgeSource links: {stats['total_knowledge_sources']} "
          f"({stats['knowledge_sources_resolved']} resolved, {stats['knowledge_sources_unresolved']} unresolved)")
    print(f"Distinct JCI citations: {stats['total_distinct_jci_citations']}")
    print(f"Wrote {args.json}")
    print(f"Wrote {args.markdown}")


if __name__ == "__main__":
    sys.exit(main())
